### ISSUE TITLE
是不是写错了？

### ISSUE THREAD

**Issue by 18039514772** [nebulasio/neb.java#16]
https://github.com/nebulasio/neb.java/blob/419ef1f3b0171eb8b0911de070ce0e6806846e53/src/main/java/io/nebulas/client/impl/HttpNebulasAdminClient.java#L115

"/v1/user/transaction"
是不是应该改成：admin
"/v1/admin/transaction"

**Comment by qywang2012** [comment]
多谢提醒，可以提交一个pull request.Thanks!

**Comment by qywang2012** [comment]
问题已修复
